### PR TITLE
Category tag filtering

### PR DESCRIPTION
**Pull request by raouf-Bouky**
hi check my code  , i added categories filter   and i also changed some of the design . 
Screenshot from 2021-12-25 03-44-09

### CODE REVIEW

**Comment by NoahErgo** [comment]
Looks amazing. @deadit if you merge this, you will want to add categories to the new submissions i added in my PR. They won't be included in this

**Comment by deadit** [comment]
Hey! Thank you for your contribition. But it is not categories filter. 
Please, use this example to understand how it needs to be implemented - https://codepen.io/georgemejia/pen/rNNQEbz.
In this task you need to add tabs and design for tabs below the search. Also, I dont like the animations for cards, maybe you can do it smoother?

**Review by deadit — CHANGES_REQUESTED** [review]
See the comment in PR

**Comment by CapsuleCorpp** [comment]
OK , let's do this !

**Comment by CapsuleCorpp** [comment]
Hello, check this . 
Screenshot from 2021-12-27 23-51-49

**Comment by deadit** [comment]
image
Hey, it has bugs. Please, check the user experience.

**Comment by glasgowm148** [comment]
image
Breaks page on mobile

**Comment by glasgowm148** [comment]
Also the cards warp slightly when you hover over them (Brave/Mac)

**Comment by NoahErgo** [comment]
@deadit please review

**Comment by NoahErgo** [comment]
@deadit can you plz review

**Comment by deadit** [comment]
checking...

**Pull request merged**
